name: check
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  check:
    runs-on: lixpine
    steps:
      - name: "checkout"
        uses: actions/checkout@v4
        with:
          github-server-url: "https://git.purr.systems"
      - name: "build"
        run: nix develop --command colmena build
