name: check
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: "checkout"
      uses: actions/checkout@v4
    - name: "set up nix"
      uses: cachix/install-nix-action@v31
    - name: "check"
      run: nix flake check